[tool.poetry]
name = "rllib_single_agent_example"
version = "0.1.0"
description = ""
authors = ["Bam4d <chrisbam4d@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
ray = {extras = ["rllib"], version = "2.1.0"}
griddly = "1.6.6"
torch = "1.12.1"
protobuf = "3.20.*"
wandb = "^0.13.5"
pygame = "^2.1.2"
gym = "0.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
